FROM php:8.2-apache

RUN apt-get update \
    && apt-get install -y --no-install-recommends libonig-dev \
    && docker-php-ext-install pdo_mysql mbstring \
    && a2enmod rewrite headers \
    && sed -i 's/Listen 80/Listen 3000/' /etc/apache2/ports.conf \
    && rm -rf /var/lib/apt/lists/*

COPY apache.alloy.conf /etc/apache2/sites-available/000-default.conf
